# Generated by Django 3.0 on 2021-08-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0002_preguntasrespondidas_usuariojuego'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='usuarioJuego',
        ),
    ]
