# Generated by Django 3.0 on 2021-08-29 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0003_auto_20210829_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuarioJuego',
            new_name='userJuego',
        ),
    ]
