# Generated by Django 3.0 on 2021-08-30 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0004_auto_20210829_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Máximo Puntaje'),
        ),
        migrations.AlterField(
            model_name='seleccionarrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='Juego.Pregunta'),
        ),
    ]
