# Generated by Django 3.0 on 2021-08-30 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0005_auto_20210829_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Juego.SeleccionarRespuesta'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='userJuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Juego.UsuarioJuego'),
        ),
    ]
