# Generated by Django 3.0 on 2021-08-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0006_auto_20210829_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntaje Obtenido'),
        ),
    ]
