# Generated by Django 3.0 on 2021-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0007_auto_20210830_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariojuego',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Puntaje total'),
        ),
    ]
